# Site settings
title: researchobject.org
email: info@esciencelab.org.uk
description: > # this means to ignore newlines until "baseurl:"
        ResearchObject.org is a community site aimed at gathering information, ideas, and interest around the topic of modernizing scholarly publication.
author: The Research Object community is coordinated by the [eScience Lab](https://esciencelab.org.uk/), The University of Manchester
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://www.esciencelab.org.uk" # the base hostname & protocol for your site
github_username: researchobject
encoding: UTF-8
permalink: pretty

markdown: kramdown

remote_theme: daattali/beautiful-jekyll
#theme: jekyll-theme-minimal
#theme: just-the-docs

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

# See https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml    


#logo: /images/logo.png
avatar: /images/logo.png
round-avatar: false
#title-img: /images/logo.png

navbar-links:
  Overview: "overview"
  "Specs & Tooling": 
    - "RO-Crate (recommended)": "https://w3id.org/ro/crate/"
    - "RO model (legacy)": "specifications"
  "Legacy":     
    - Scopes: "scopes"
    - "Related":
      - Clinicalcodes.org: "initiative/clinicalcodes"
      - Code as a Research Object: "initiative/code-as-a-research-object"
      - Combine Archive: "initiative/combine-archive"
      - DCAT: "initiative/data-catalog-vocabulary-dcat"
      - Data FAIRport: "initiative/data-fairport-initiative"
      - Dataset Descriptions: "initiative/HCLS Community Profile: dataset-descriptions-hcls-community-profile"
      - Digital Object: "initiative/digital-object-architecture"
      - Docker: "initiative/docker"
      - Github: "initiative/github"
      - iPython Notebooks: "initiative/ipython-notebooks"
      - ISA: "initiative/isa"
      - JATS: "initiative/jats"
      - latex2Latex2RO: "initiative/ro"
      - Minimum Information Model: "initiative/mim"
      - myExperiment.org: "initiative/myexperiment-org"
      - Nanopublications: "initiative/nanopublications"
      - OAI-ORE (Object Reuse and Exchange): "initiative/oai-ore"
      - OKF Ckan: "initiative/okf-ckan"
      - OKF Data Packages: "initiative/okf-data-packages"
      - Open Annotation Model: "initiative/open-annotation-model"
      - Open Researcher and Contributor ID (ORCID): "initiative/orcid"
      - PAV: "initiative/pav"
      - Projects.ac: "initiative/projects-ac"
      - PROV: "initiative/prov-provenance-model"
      - Reproducible Research in R: "initiative/reproducible-research-in-r"
      - ReproZip: "initiative/reprozip"
      - Research Object Model: "initiative/research-object-model"
      - RightField: "initiative/rightfield"
      - RO Bundle (Zip): "initiative/ro-bundle-zip"
      - SEEK: "initiative/seek"
      - STELAR Asthma e-Lab: "initiative/stelar"
      - taverna-prov: "initiative/Taverna Workflow Engine Prov Export: taverna-prov-taverna-workflow-engine-prov-export"
      - VIVO-ISF Ontology: "initiative/vivo-isf-ontology"
  Workshops:
    - RO2019: "ro2019"
    - RO2018: "ro2018"
  Publications: "publications"
  About: "about"

