# Site settings
title: researchobject.org
email: info@esciencelab.org.uk
description: > # this means to ignore newlines until "baseurl:"
        ResearchObject.org is a community site aimed at gathering information, ideas, and interest around the topic of modernizing scholarly publication.
author: The Research Object community is coordinated by the eScience Lab at The University of Manchester, UK
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://www.esciencelab.org.uk" # the base hostname & protocol for your site
github_username: researchobject
encoding: UTF-8
permalink: pretty

markdown: kramdown

remote_theme: daattali/beautiful-jekyll
#theme: jekyll-theme-minimal
#theme: just-the-docs

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

# See https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml    


logo: /images/logo.png
round-avatar: false
title-img: /images/logo.png

navbar-links:
  Overview: "overview"
  Specifications:
    - "RO-Crate (recommended)": "https://w3id.org/ro/crate/"
    - "RO model (legacy)": "specs"
  Scopes: "scopes"
  Workshops:
    - RO2019: "ro2019"
    - RO2018: "ro2018"
  Publications: "publications"
  Related: "initiative"
  About: "about"

date_format: "%-d %B %Y"  

collections:
  initiative:
    output: true
    permalink: /:collection/:path/ # Note, trailing / needed to avoid .html

